module.exports = `
  CREATE TABLE IF NOT EXISTS MenuItems (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MenuItemName VARCHAR(255) NOT NULL,
    CategoryId INT NOT NULL,
    Price INT NOT NULL,
    image_url TEXT,
    Insupply BOOLEAN DEFAULT TRUE,
    CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryId) REFERENCES Category(Id) ON DELETE CASCADE
  );
`;
